#!/bin/bash

var_1=1

for i in Stone.png Grass.png Dirt.png Cobblestone.png Wooden_Plank.png Sapling.png Bedrock.png Water.png Water.png Lava.png Lava.png Sand.png Gravel.png Gold_\(Ore\).png Iron_\(Ore\).png Coal_\(Ore\).png Wood.png Leaves.png Sponge.png Glass.png Lapis_Lazuli_\(Ore\).png Lapis_Lazuli_\(Block\).png Dispenser.png Sandstone.png Note_Block.png Bed.png Powered_Rail_Off.png Detector_Rail.png Sticky_Piston.png WebBlock.png Tall_Grass.png Dead_Bush.png Piston.png Block_34.png White_Wool.png Technical_blocks.png Dandelion.png Rose.png Brown_Mushroom.png Red_Mushroom.png Gold_\(Block\).png Iron_\(Block\).png Double_Stone_Slab.png Stone_Slab.png Brick_\(Block\).png TNT.png Bookshelf.png Moss_Stone.png Obsidian.png Torch.png Fire.png Monster_Spawner.png Wooden_Stairs.png Chest.png Redstone_\(Wire,Inventory\).png Diamond_\(Ore\).png Diamond_\(Block\).png Crafting_Table.png Crops.png Farmland.png Furnace.png Furnace_\(Active\).png Sign.png Wooden_Door.png Ladders.png Rails.png Cobblestone_Stairs.png Wall_Sign.png Lever.png Stone_Pressure_Plate.png Iron_Door.png Wooden_Pressure_Plate.png Redstone_\(Ore\).png Redstone_\(Ore\).png Redstone_\(Torch,_Inactive\).png Redstone_\(Torch,_Active\).png Stone_Button.png Snow.png Ice.png Snow_\(Block\).png Cactus.png Clay_\(Block\).png Sugar_Cane.png Jukebox.png Fence.png Pumpkin.png Netherrack.png Soul_Sand.png Glowstone_\(Block\).png Portal.png Jack-O-Lantern.png Cake.png Redstone_\(Repeater,_Inactive\).png Redstone_\(Repeater,_Active\).png Locked_Chest.png Trapdoor.png Stone.png Stone_Brick.png Huge_Brown_Mushroom.png Huge_Red_Mushroom.png Iron_Bars.png Glass_Pane.png Melon_\(Block\).png Seed_Stem.png Seed_Stem.png Vine.png Fence_Gate_\(Closed\).png Brick_Stairs.png Stone_Brick_Stairs.png Mycelium.png Lily_Pad.png Nether_Brick.png Nether_Brick_Fence.png Nether_Brick_Stairs.png Nether_Wart.png Enchantment_Table.png Brewing_Stand.png Cauldron.png End_Portal.png End_Portal_Frame.png End_Stone.png Dragon_Egg.png Redstone_Lamp.png Redstone_Lamp_\(Active\).png Wooden_Plank.png Oak-Wood_Slab.png Cocoa_Plant.png Sandstone_Stairs.png Emerald_Ore2.png Ender_Chest.png Tripwire_Hook.png Tripwire.png Block_of_Emerald.png Spruce_Wood_Stairs.png Birch_Wood_Stairs.png Jungle_Wood_Stairs.png Adventure_Mode_Control_Block.png Beacon_Block.png Cobblestone_Wall.png Flower_Pot.png Carrot_\(Block\).png Potatoes_\(Block\).png Wooden_Button.png Mob_Head.png Anvil.png Trapped_Chest.png Weighted_Pressure_Plate_\(Light\).png Weighted_Pressure_Plate_\(Heavy\).png Redstone_Comparator_\(inactive\).png Redstone_Comparator_\(active\).png Daylight_Detector.png Block_of_Redstone.png Nether_Quartz_Ore.png Hopper.png Block_of_Nether_Quartz.png Quartz_Stairs.png Activator_Rail.png Dropper.png White_Stained_Clay.png Hay_Block.png White_Carpet.png Hardened_Clay.png Block_of_Coal.png; do

cp $i $var_1.png
var_1=`expr $var_1 + 1`

done

